// Code generated by "stringer -type=coreType"; DO NOT EDIT.

package zapper

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CONSOLE-0]
	_ = x[SENTRY-1]
	_ = x[FILE-2]
	_ = x[JSON-3]
}

const _coreType_name = "CONSOLESENTRYFILEJSON"

var _coreType_index = [...]uint8{0, 7, 13, 17, 21}

func (i coreType) String() string {
	if i < 0 || i >= coreType(len(_coreType_index)-1) {
		return "coreType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _coreType_name[_coreType_index[i]:_coreType_index[i+1]]
}
