// Code generated by "stringer -type=Level"; DO NOT EDIT.

package zapper

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Debug - -1]
	_ = x[Info-0]
	_ = x[Warn-1]
	_ = x[Error-2]
	_ = x[DPanic-3]
	_ = x[Panic-4]
	_ = x[Fatal-5]
}

const _Level_name = "DebugInfoWarnErrorDPanicPanicFatal"

var _Level_index = [...]uint8{0, 5, 9, 13, 18, 24, 29, 34}

func (i Level) String() string {
	i -= -1
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
