// Code generated by "stringer -type=TimeFormat"; DO NOT EDIT.

package zapper

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ISO8601-0]
	_ = x[RFC3339-1]
	_ = x[RFC3339NANO-2]
}

const _TimeFormat_name = "ISO8601RFC3339RFC3339NANO"

var _TimeFormat_index = [...]uint8{0, 7, 14, 25}

func (i TimeFormat) String() string {
	if i < 0 || i >= TimeFormat(len(_TimeFormat_index)-1) {
		return "TimeFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimeFormat_name[_TimeFormat_index[i]:_TimeFormat_index[i+1]]
}
