// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	zap "go.uber.org/zap"
)

// logFunc is an autogenerated mock type for the logFunc type
type logFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, args
func (_m *logFunc) Execute(_a0 *zap.SugaredLogger, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type mockConstructorTestingTnewLogFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newLogFunc creates a new instance of logFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newLogFunc(t mockConstructorTestingTnewLogFunc) *logFunc {
	mock := &logFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
